apiVersion: v1
kind: BuildConfig
metadata:
  name: blue-pipeline
  labels:
    name: blue-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "blue", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
        stage ('dev')
        {
        openshiftDeploy(deploymentConfig: 'blue')
        }
        stage ('uat')
        {
        openshiftScale(deploymentConfig: 'blue',replicaCount: '2')
        }
        stage ('prod')
        {
        input('Approve?')
        openshiftScale(deploymentConfig: 'blue',replicaCount: '2')
        }
        }
  output:
  resources:
  postCommit:
